# Generated by Django 2.2.2 on 2019-06-28 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_coin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
